<?php
/**
 * ACF Field Registrar
 *
 * @package ChoctawNation\CNHSA_Federation\Tests
 */

namespace ChoctawNation\CNHSA_Federation\Tests;

/**
 * Class ACF Fields
 * Registers ACF fields for testing purposes.
 */
class ACF_Fields {
	/**
	 * Register ACF fields for testing.
	 *
	 * @param 'all'|'locations'|'services' $type The type of fields to register.
	 * @throws \InvalidArgumentException If an invalid type is provided.
	 */
	public static function register_fields( string $type = 'all' ) {
		$allowed_params = array( 'all', 'locations', 'services' );
		if ( ! in_array( $type, $allowed_params, true ) ) {
			throw new \InvalidArgumentException( esc_textarea( 'Invalid type parameter. Allowed values are: ' . implode( ', ', $allowed_params ) ) );
		}
		if ( 'all' === $type || 'locations' === $type ) {
			self::register_location_fields();
		}

		if ( 'all' === $type || 'services' === $type ) {
			self::register_service_fields();
		}
	}

	/**
	 * Register ACF fields for the 'locations' post type.
	 */
	private static function register_location_fields() {
		acf_add_local_field_group(
			array(
				'key'      => 'group_6116e4e122227',
				'title'    => 'Post Type — Locations',
				'fields'   => array(
					array(
						'key'               => 'field_615b6d1471796',
						'label'             => 'Choctaw or External Location',
						'name'              => 'choctaw_or_external_location',
						'aria-label'        => '',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'choctaw'  => 'Choctaw Location',
							'external' => 'External Location',
						),
						'default_value'     => 'choctaw',
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'return_format'     => 'value',
						'ajax'              => 0,
						'placeholder'       => '',
						'create_options'    => 0,
						'save_options'      => 0,
					),
					array(
						'key'               => 'field_6116e5d28dc2f',
						'label'             => 'Photo',
						'name'              => 'photo',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_615b6d1471796',
									'operator' => '==',
									'value'    => 'choctaw',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'preview_size'      => 'medium',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
					array(
						'key'               => 'field_615b6d4771797',
						'label'             => 'Map',
						'name'              => 'map',
						'aria-label'        => '',
						'type'              => 'google_map',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_615b6d1471796',
									'operator' => '==',
									'value'    => 'external',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'center_lat'        => '33.973972679562536',
						'center_lng'        => '-96.39882601893775',
						'zoom'              => 16,
						'height'            => '',
					),
					array(
						'key'               => 'field_6116e5368dc2e',
						'label'             => 'Type',
						'name'              => 'type',
						'aria-label'        => '',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'Commerce'                 => 'Commerce',
							'Community Center'         => 'Community Center',
							'Coworking Center'         => 'Coworking Center',
							'Cultural Services'        => 'Cultural Services',
							'Education'                => 'Education',
							'Food Distribution Center' => 'Food Distribution Center',
							'Government'               => 'Government',
							'Health Facility'          => 'Health Facility',
							'Judicial'                 => 'Judicial',
							'Recycling Center'         => 'Recycling Center',
							'Wellness Center'          => 'Wellness Center',
							'Casinos'                  => 'Casinos',
							'External'                 => 'External',
						),
						'default_value'     => false,
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'return_format'     => 'value',
						'ajax'              => 0,
						'placeholder'       => '',
						'create_options'    => 0,
						'save_options'      => 0,
					),
					array(
						'key'               => 'field_6116e4e38dc2a',
						'label'             => 'Address',
						'name'              => 'address',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_615b6d1471796',
									'operator' => '!=',
									'value'    => 'virtual',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6116e50e8dc2b',
						'label'             => 'City, State, & Zip',
						'name'              => 'city_state_zip',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_615b6d1471796',
									'operator' => '!=',
									'value'    => 'virtual',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6116e5238dc2c',
						'label'             => 'Phone Number',
						'name'              => 'phone_number',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_615b6d1471796',
									'operator' => '==',
									'value'    => 'choctaw',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_620d5f8722fa3',
						'label'             => 'Phone Number',
						'name'              => 'phone_number',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_615b6d1471796',
									'operator' => '==',
									'value'    => 'external',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6116e52f8dc2d',
						'label'             => 'Additional Phone Number',
						'name'              => 'additional_phone_number',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6136356822bfb',
						'label'             => 'Fax Number',
						'name'              => 'fax_number',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6116ea25d5f08',
						'label'             => 'Directions Link',
						'name'              => 'directions_link',
						'aria-label'        => '',
						'type'              => 'url',
						'instructions'      => 'Go to https://www.google.com/maps/ and search address. Then press the "Share" button and copy the URL here.',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
					),
					array(
						'key'                => 'field_68c8635ce49a7',
						'label'              => 'CNHSA ID',
						'name'               => 'cnhsa_id',
						'aria-label'         => '',
						'type'               => 'text',
						'instructions'       => 'CNHSA post id for additional facility or clinic. Used to send data to the site.',
						'required'           => 1,
						'conditional_logic'  => array(
							array(
								array(
									'field'    => 'field_6116e5368dc2e',
									'operator' => '==',
									'value'    => 'Health Facility',
								),
							),
						),
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 0,
						'default_value'      => '',
						'maxlength'          => '',
						'allow_in_bindings'  => 0,
						'placeholder'        => '',
						'prepend'            => '',
						'append'             => '',
					),
				),
				'location' => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'locations',
						),
					),
				),
			// 'menu_order' => 0,
			// 'position' => 'acf_after_title',
			// 'style' => 'default',
			// 'label_placement' => 'top',
			// 'instruction_placement' => 'label',
			// 'hide_on_screen' => '',
			// 'active' => true,
			// 'description' => '',
			// 'show_in_rest' => 1,
			// 'display_title' => '',
			)
		);
	}

	/**
	 * Register ACF fields for the 'services' post type.
	 */
	private static function register_service_fields() {
		acf_add_local_field_group(
			array(
				'key'      => 'group_610428917c18a',
				'title'    => 'Post Type — Services',
				'fields'   => array(
					array(
						'key'               => 'field_6244bde565894',
						'label'             => 'Brief Description',
						'name'              => 'archive_content',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'maxlength'         => 400,
						'rows'              => '',
						'new_lines'         => '',
					),
					array(
						'key'                => 'field_698f915a1579e',
						'label'              => 'Eligibility',
						'name'               => '',
						'aria-label'         => '',
						'type'               => 'tab',
						'instructions'       => '',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 1,
						'placement'          => 'top',
						'endpoint'           => 0,
						'selected'           => 0,
					),
					array(
						'key'               => 'field_614372d95296b',
						'label'             => 'CNHSA Eligibility Guidelines',
						'name'              => 'cnhsa_eligibility_guidelines',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => 'Check this to display a bullet with link to guidelines for CNHSA.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'ui'                => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'               => 'field_610ad5964618c',
						'label'             => 'Eligibility Requirements',
						'name'              => 'eligibility_requirements',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'collapsed'         => '',
						'min'               => 0,
						'max'               => 0,
						'layout'            => 'block',
						'button_label'      => 'Add Requirement',
						'sub_fields'        => array(
							array(
								'key'               => 'field_610ad5a14618d',
								'label'             => 'Requirement',
								'name'              => 'requirement',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '85',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'parent_repeater'   => 'field_610ad5964618c',
							),
							array(
								'key'               => 'field_615372214edbb',
								'label'             => 'Nested List?',
								'name'              => 'nested_list',
								'aria-label'        => '',
								'type'              => 'true_false',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '15',
									'class' => '',
									'id'    => '',
								),
								'message'           => '',
								'default_value'     => 0,
								'ui'                => 0,
								'ui_on_text'        => '',
								'ui_off_text'       => '',
								'parent_repeater'   => 'field_610ad5964618c',
							),
							array(
								'key'               => 'field_6153723a4edbc',
								'label'             => 'List',
								'name'              => 'list',
								'aria-label'        => '',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_615372214edbb',
											'operator' => '==',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '100',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 1,
								'max'               => 0,
								'layout'            => 'table',
								'button_label'      => 'Add List Item',
								'sub_fields'        => array(
									array(
										'key'             => 'field_615372484edbd',
										'label'           => 'List Item',
										'name'            => 'list_item',
										'aria-label'      => '',
										'type'            => 'text',
										'instructions'    => '',
										'required'        => 1,
										'conditional_logic' => array(
											array(
												array(
													'field'    => 'field_615372214edbb',
													'operator' => '==',
													'value'    => '1',
												),
											),
										),
										'wrapper'         => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'   => '',
										'placeholder'     => '',
										'prepend'         => '',
										'append'          => '',
										'maxlength'       => '',
										'parent_repeater' => 'field_6153723a4edbc',
									),
								),
								'rows_per_page'     => 20,
								'parent_repeater'   => 'field_610ad5964618c',
							),
						),
						'rows_per_page'     => 20,
					),
					array(
						'key'                => 'field_698f917e1579f',
						'label'              => 'Application Details',
						'name'               => '',
						'aria-label'         => '',
						'type'               => 'tab',
						'instructions'       => '',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 1,
						'placement'          => 'top',
						'endpoint'           => 0,
						'selected'           => 0,
					),
					array(
						'key'               => 'field_610ad8d846192',
						'label'             => 'How to Apply Paragraph',
						'name'              => 'how_to_apply',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'maxlength'         => '',
						'rows'              => '',
						'new_lines'         => '',
					),
					array(
						'key'               => 'field_6104289ce2487',
						'label'             => 'Apply Online?',
						'name'              => 'apply_online',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '25',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'ui'                => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'               => 'field_610d5ff3f74ee',
						'label'             => 'Online Application URL',
						'name'              => 'online_application_url',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_6104289ce2487',
									'operator' => '==',
									'value'    => '1',
								),
							),
						),
						'wrapper'           => array(
							'width' => '75',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
					),
					array(
						'key'               => 'field_610ad72a4618e',
						'label'             => 'Mail-In Application Address',
						'name'              => 'application_address',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6112f1409a697',
								'label'             => 'Name',
								'name'              => 'name',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => 'Name of Mailing Location',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '25',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
							array(
								'key'               => 'field_610ad7664618f',
								'label'             => 'Address',
								'name'              => 'address',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => 'Use format: 999 Name St #123',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '25',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
							array(
								'key'               => 'field_610ad77246190',
								'label'             => 'City, State & Zip Code',
								'name'              => 'city_state_zip',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => 'Use format: City, ST 99999',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '25',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
							array(
								'key'               => 'field_610ad78a46191',
								'label'             => 'Fax Number',
								'name'              => 'fax_number',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => 'Use the format: 999-999-9999',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '25',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
						),
					),
					array(
						'key'                       => 'field_6127fb87e6284',
						'label'                     => 'Inside or Outside Reservation',
						'name'                      => 'inside_or_outside_reservation',
						'aria-label'                => '',
						'type'                      => 'checkbox',
						'instructions'              => '',
						'required'                  => 1,
						'conditional_logic'         => 0,
						'wrapper'                   => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'                   => array(
							'inside'  => 'Inside Reservation',
							'outside' => 'Outside Reservation',
						),
						'allow_custom'              => 0,
						'default_value'             => array(
							0 => 'inside',
						),
						'layout'                    => 'vertical',
						'toggle'                    => 0,
						'return_format'             => 'value',
						'save_custom'               => 0,
						'custom_choice_button_text' => 'Add new choice',
					),
					array(
						'key'               => 'field_610d6035f0019',
						'label'             => 'Is Application Always Open?',
						'name'              => 'is_application_always_open',
						'aria-label'        => '',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'Yes' => 'Yes',
							'No'  => 'No',
						),
						'default_value'     => false,
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'return_format'     => 'value',
						'ajax'              => 0,
						'placeholder'       => '',
						'create_options'    => 0,
						'save_options'      => 0,
					),
					array(
						'key'                     => 'field_610428c4e2488',
						'label'                   => 'Application Period Start',
						'name'                    => 'application_period_start',
						'aria-label'              => '',
						'type'                    => 'date_picker',
						'instructions'            => '',
						'required'                => 1,
						'conditional_logic'       => array(
							array(
								array(
									'field'    => 'field_610d6035f0019',
									'operator' => '==',
									'value'    => 'No',
								),
							),
						),
						'wrapper'                 => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'display_format'          => 'm/d/Y',
						'return_format'           => 'm/d/Y',
						'first_day'               => 0,
						'default_to_current_date' => 0,
					),
					array(
						'key'                     => 'field_610428dee2489',
						'label'                   => 'Application Period End',
						'name'                    => 'application_period_end',
						'aria-label'              => '',
						'type'                    => 'date_picker',
						'instructions'            => '',
						'required'                => 1,
						'conditional_logic'       => array(
							array(
								array(
									'field'    => 'field_610d6035f0019',
									'operator' => '==',
									'value'    => 'No',
								),
							),
						),
						'wrapper'                 => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'display_format'          => 'm/d/Y',
						'return_format'           => 'm/d/Y',
						'first_day'               => 0,
						'default_to_current_date' => 0,
					),
					array(
						'key'               => 'field_610d9b2ff1cff',
						'label'             => 'Application Period Open',
						'name'              => 'application_period_open',
						'aria-label'        => '',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'Yes' => 'Yes',
							'No'  => 'No',
						),
						'default_value'     => 'Yes',
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'return_format'     => 'value',
						'ajax'              => 0,
						'placeholder'       => '',
						'create_options'    => 0,
						'save_options'      => 0,
					),
					array(
						'key'                => 'field_698f91f425f4e',
						'label'              => 'Additional Content',
						'name'               => '',
						'aria-label'         => '',
						'type'               => 'tab',
						'instructions'       => '',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 1,
						'placement'          => 'top',
						'endpoint'           => 0,
						'selected'           => 0,
					),
					array(
						'key'               => 'field_610ad90446193',
						'label'             => 'Additional Information',
						'name'              => 'additional_information',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
						'delay'             => 0,
					),
					array(
						'key'                => 'field_698f920125f4f',
						'label'              => 'FAQs Accordion',
						'name'               => '',
						'aria-label'         => '',
						'type'               => 'accordion',
						'instructions'       => '',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 1,
						'open'               => 0,
						'multi_expand'       => 0,
						'endpoint'           => 0,
					),
					array(
						'key'               => 'field_61f46e4362efa',
						'label'             => 'Accordion Title',
						'name'              => 'faq_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_63161d48211a5',
						'label'             => 'Accordion in modal?',
						'name'              => 'faq_in_modal',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'ui'                => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'               => 'field_61f46445ede6a',
						'label'             => 'Accordion Section',
						'name'              => 'faq',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'collapsed'         => '',
						'min'               => 0,
						'max'               => 0,
						'layout'            => 'table',
						'button_label'      => 'Add Accordion',
						'sub_fields'        => array(
							array(
								'key'               => 'field_61f4648aede6b',
								'label'             => 'Question',
								'name'              => 'question',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '30',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'parent_repeater'   => 'field_61f46445ede6a',
							),
							array(
								'key'               => 'field_61f464a7ede6c',
								'label'             => 'Answer',
								'name'              => 'answer',
								'aria-label'        => '',
								'type'              => 'wysiwyg',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '70',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'tabs'              => 'all',
								'toolbar'           => 'basic',
								'media_upload'      => 0,
								'delay'             => 0,
								'parent_repeater'   => 'field_61f46445ede6a',
							),
						),
						'rows_per_page'     => 20,
					),
					array(
						'key'                => 'field_698f922025f50',
						'label'              => 'FAQs (End)',
						'name'               => '',
						'aria-label'         => '',
						'type'               => 'accordion',
						'instructions'       => '',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 1,
						'open'               => 0,
						'multi_expand'       => 0,
						'endpoint'           => 1,
					),
					array(
						'key'               => 'field_6245d90d9beda',
						'label'             => 'Form Title',
						'name'              => 'form_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6245d7191b0cc',
						'label'             => 'Form',
						'name'              => 'form',
						'aria-label'        => '',
						'type'              => 'forms',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'allow_null'        => 1,
						'multiple'          => 0,
					),
					array(
						'key'                => 'field_698f9191157a0',
						'label'              => 'Additional Information',
						'name'               => '',
						'aria-label'         => '',
						'type'               => 'tab',
						'instructions'       => '',
						'required'           => 0,
						'conditional_logic'  => 0,
						'wrapper'            => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'relevanssi_exclude' => 0,
						'placement'          => 'top',
						'endpoint'           => 0,
						'selected'           => 0,
					),
					array(
						'key'               => 'field_610ad91d46194',
						'label'             => 'Related Media',
						'name'              => 'related_media',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'collapsed'         => '',
						'min'               => 0,
						'max'               => 0,
						'layout'            => 'table',
						'button_label'      => 'Add Related Media',
						'sub_fields'        => array(
							array(
								'key'               => 'field_610ad96546195',
								'label'             => 'Link Text',
								'name'              => 'link_text',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'parent_repeater'   => 'field_610ad91d46194',
							),
							array(
								'key'               => 'field_610ad97846196',
								'label'             => 'File or Link',
								'name'              => 'file_or_link',
								'aria-label'        => '',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'pdf'           => 'PDF',
									'video'         => 'Embedded Video',
									'external_link' => 'Link (external)',
									'internal_link' => 'Link (internal)',
								),
								'default_value'     => false,
								'allow_null'        => 0,
								'multiple'          => 0,
								'ui'                => 0,
								'return_format'     => 'value',
								'ajax'              => 0,
								'placeholder'       => '',
								'create_options'    => 0,
								'save_options'      => 0,
								'parent_repeater'   => 'field_610ad91d46194',
							),
							array(
								'key'               => 'field_6112e91c0f0b9',
								'label'             => 'PDF',
								'name'              => 'pdf',
								'aria-label'        => '',
								'type'              => 'file',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_610ad97846196',
											'operator' => '==',
											'value'    => 'PDF',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'url',
								'library'           => 'all',
								'min_size'          => '',
								'max_size'          => '',
								'mime_types'        => 'pdf',
								'parent_repeater'   => 'field_610ad91d46194',
							),
							array(
								'key'               => 'field_6112e93d0f0ba',
								'label'             => 'Embedded Video',
								'name'              => 'embedded_video',
								'aria-label'        => '',
								'type'              => 'oembed',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_610ad97846196',
											'operator' => '==',
											'value'    => 'video',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'width'             => '',
								'height'            => '',
								'parent_repeater'   => 'field_610ad91d46194',
							),
							array(
								'key'               => 'field_6112e9820f0bc',
								'label'             => 'External Link',
								'name'              => 'external_link',
								'aria-label'        => '',
								'type'              => 'url',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_610ad97846196',
											'operator' => '==',
											'value'    => 'external_link',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'parent_repeater'   => 'field_610ad91d46194',
							),
							array(
								'key'               => 'field_6112e96b0f0bb',
								'label'             => 'Internal Link',
								'name'              => 'internal_link',
								'aria-label'        => '',
								'type'              => 'page_link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_610ad97846196',
											'operator' => '==',
											'value'    => 'internal_link',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'post_type'         => '',
								'taxonomy'          => '',
								'allow_null'        => 0,
								'allow_archives'    => 1,
								'multiple'          => 0,
								'parent_repeater'   => 'field_610ad91d46194',
							),
						),
						'rows_per_page'     => 20,
					),
					array(
						'key'               => 'field_6112ea31e8b31',
						'label'             => 'Contact Information',
						'name'              => 'contact_information',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6112ea4ee8b32',
								'label'             => 'Phone Number(s)',
								'name'              => 'phone_numbers',
								'aria-label'        => '',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 0,
								'max'               => 0,
								'layout'            => 'table',
								'button_label'      => 'Add Phone Number',
								'sub_fields'        => array(
									array(
										'key'             => 'field_6112ea63e8b33',
										'label'           => 'Phone Number',
										'name'            => 'phone_number',
										'aria-label'      => '',
										'type'            => 'text',
										'instructions'    => 'Use the format: 999-999-9999',
										'required'        => 1,
										'conditional_logic' => 0,
										'wrapper'         => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'   => '',
										'placeholder'     => '',
										'prepend'         => '',
										'append'          => '',
										'maxlength'       => '',
										'parent_repeater' => 'field_6112ea4ee8b32',
									),
								),
								'rows_per_page'     => 20,
							),
							array(
								'key'               => 'field_6112ea84e8b34',
								'label'             => 'Contact Form?',
								'name'              => 'contact_form',
								'aria-label'        => '',
								'type'              => 'true_false',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '25',
									'class' => '',
									'id'    => '',
								),
								'message'           => '',
								'default_value'     => 1,
								'ui'                => 0,
								'ui_on_text'        => '',
								'ui_off_text'       => '',
							),
							array(
								'key'               => 'field_61169ca81c72e',
								'label'             => 'Contact Email',
								'name'              => 'contact_email',
								'aria-label'        => '',
								'type'              => 'email',
								'instructions'      => 'Only allows 1 email address',
								'required'          => 1,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6112ea84e8b34',
											'operator' => '==',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '75',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_612fc6cfa2da0',
								'label'             => 'External Contact Link(s)',
								'name'              => 'external_contact_link',
								'aria-label'        => '',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 0,
								'max'               => 0,
								'layout'            => 'table',
								'button_label'      => 'Add External Contact Link',
								'sub_fields'        => array(
									array(
										'key'             => 'field_612fc6dfa2da1',
										'label'           => 'Button Text',
										'name'            => 'button_text',
										'aria-label'      => '',
										'type'            => 'text',
										'instructions'    => '',
										'required'        => 1,
										'conditional_logic' => 0,
										'wrapper'         => array(
											'width' => '50',
											'class' => '',
											'id'    => '',
										),
										'default_value'   => '',
										'placeholder'     => '',
										'prepend'         => '',
										'append'          => '',
										'maxlength'       => '',
										'parent_repeater' => 'field_612fc6cfa2da0',
									),
									array(
										'key'             => 'field_612fc6eca2da2',
										'label'           => 'URL',
										'name'            => 'url',
										'aria-label'      => '',
										'type'            => 'url',
										'instructions'    => '',
										'required'        => 1,
										'conditional_logic' => 0,
										'wrapper'         => array(
											'width' => '50',
											'class' => '',
											'id'    => '',
										),
										'default_value'   => '',
										'placeholder'     => '',
										'parent_repeater' => 'field_612fc6cfa2da0',
									),
								),
								'rows_per_page'     => 20,
							),
						),
					),
					array(
						'key'                  => 'field_61042907e248a',
						'label'                => 'Service Location',
						'name'                 => 'location',
						'aria-label'           => '',
						'type'                 => 'post_object',
						'instructions'         => '',
						'required'             => 1,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'post_type'            => array(
							0 => 'locations',
						),
						'taxonomy'             => '',
						'allow_null'           => 0,
						'multiple'             => 1,
						'return_format'        => 'object',
						'ui'                   => 1,
						'bidirectional_target' => array(),
					),
					array(
						'key'               => 'field_61fd624b4d1d3',
						'label'             => 'PIxel/Script Embed',
						'name'              => 'pixel',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => 'Input Pixel/Script to be added to the header of this page.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'maxlength'         => '',
						'rows'              => '',
						'new_lines'         => '',
					),
				),
				'location' => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'services',
						),
						array(
							'param'    => 'post_template',
							'operator' => '==',
							'value'    => 'default',
						),
					),
				),
			// 'menu_order' => 0,
			// 'position' => 'normal',
			// 'style' => 'default',
			// 'label_placement' => 'top',
			// 'instruction_placement' => 'label',
			// 'hide_on_screen' => '',
			// 'active' => true,
			// 'description' => '',
			// 'show_in_rest' => 1,
			// 'display_title' => 'Programs & Services',
			)
		);
	}
}
